### ISSUE TITLE
extract `formatForType`

### ISSUE THREAD

**Issue by sindresorhus** [gruntjs/grunt-lib-contrib#10]
@OliverJAsh since you were the one that added `formatForType`, would you be willing to extract it out into a separate module? I'm trying to get rid of grunt-lib-contrib.

**Comment by tkellen** [comment]
It's actually not used anywhere--you can nuke it.

**Comment by tkellen** [comment]
The basic concept behind what it was supposed to do is extracted already, but is not currently in use anywhere:
https://github.com/tkellen/node-wrapfor

**Comment by sindresorhus** [comment]
Awesome :)

**Comment by tkellen** [comment]
If you feel like delving into the stupid amd/commonjs/etc wrappers that we have on every plugin and centralizing them to use wrapfor I'll give you my firstborn son or, or something.

**Comment by sindresorhus** [comment]
lol, no, not particularly. IMHO it should be a separate grunt task, and none of the existing ones should have that option.

**Comment by tkellen** [comment]
agreed--once grunt manages intermediary files automatically.
