### ISSUE TITLE
Impossible to install grunt-lib-contrib due to some obscure dependencies

### ISSUE THREAD

**Issue by jdespatis** [gruntjs/grunt-lib-contrib#8]
Hello,

When doing npm install grunt-lib-contrib, in order to install this grunt plugin, I get this:

```
npm http GET https://registry.npmjs.org/grunt-lib-contrib
npm http 304 https://registry.npmjs.org/grunt-lib-contrib
npm http GET https://registry.npmjs.org/zlib-browserify/0.0.1
npm http 304 https://registry.npmjs.org/zlib-browserify/0.0.1
npm WARN package.json eventemitter2@0.4.11 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
grunt-lib-contrib@0.6.1 /usr/lib/node_modules/grunt-lib-contrib
└── zlib-browserify@0.0.1
```

The fact is zlib-browserify depends on eventemitter, containing, I think, some typos errors in the package.json...

One solution, maybe, would be to use better dependencies for grunt-lib-contrib ? (eventemitter is quite old)

Thanks for your work (I need grunt-lib-contrib for grunt-jsduck indeed)

**Comment by shama** [comment]
Hi! It looks like `eventemitter2` just needs to update their package.json repository property: https://github.com/hij1nx/EventEmitter2/blob/master/package.json#L20 `eventemitter2` gets about 40k installs a week so it's not that obscure ;) https://npmjs.org/package/eventemitter2

I'll send them a PR later today, thanks!

Just fyi, Grunt depends on `eventemitter2` directly and it's not a dep of `zlib-browserify`. You can view the deps with `npm view packagename`.

**Comment by jdespatis** [comment]
Thanks
