### ISSUE TITLE
extract `getNamespaceDeclaration`

### ISSUE THREAD

**Issue by sindresorhus** [gruntjs/grunt-lib-contrib#9]
@lazd since you were the one that added `getNamespaceDeclaration`, would you be willing to extract it out into a separate module? I'm trying to get rid of grunt-lib-contrib.

**Comment by lazd** [comment]
Absolutely. I'll publish something this weekend.

**Comment by sindresorhus** [comment]
Awesome, thanks for the quick response :)

**Comment by lazd** [comment]
[Published as `nsdeclare`](https://www.npmjs.org/package/nsdeclare) and ready for consumption! The usage is slightly different, but it should meet any use case Grunt plugins have.

I've published a new version of `gulp-declare` that makes use of `nsdeclare`, that can be used as an example when using `nsdeclare` in Grunt plugins: https://www.npmjs.org/package/gulp-declare

**Comment by sindresorhus** [comment]
Awesome, thanks man :)
